### PR TITLE
Move config.json to config.json.sample

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
This makes it easier to have your own config.json and don't lose changes/get
conflicts if you update directly from the repository

### CODE REVIEW

**Comment by mathias-baumann-sociomantic** [comment]
I added the requested changes and rebased on the latest master

**Review by codebam — COMMENTED** [review]
"by changing copying the sample config file"

**Comment by codebam** [comment]
oh my bad. for some reason the diff didn't show it correctly. it seems to be displaying properly inside the README

**Comment by mathias-baumann-sociomantic** [comment]
No you were right, it is wrong. But I see you took care of it already :)

**Pull request merged**
