### PR TITLE
Guarantee removal of temporal payload file

### PR DESCRIPTION
**Pull request by kpriceyahoo**
Guarantee that the temporal payload file is removed even if an
exception occurs during storage of the temporary payload file
or during execution of the hook scripts.

### CODE REVIEW

**Comment by kpriceyahoo** [comment]
This is really minor, obviously, just something I noticed when reviewing this script.

**Comment by kpriceyahoo** [comment]
There exists a race condition. The script may exist and be executable at the time of the check, but be removed or have its permissions changed by the time it is executed.

**Comment by kpriceyahoo** [comment]
There's also another case that I meant to catch but I realize this PR misses, which is if an exception is caused when storing the payload initially. The with block will close the file handle in that case, but the file won't be removed.

**Comment by ishitatsuyuki** [comment]
Warning: `with` doesn't close the fd if any exception occured during `write()`.

**Comment by ishitatsuyuki** [comment]
Oops, seems I was wrong. Sorry for the confusion.

**Pull request closed without merging**
